### ISSUE TITLE
Multiple fault codes on ZE0 2012 after Chademo

### ISSUE THREAD

**Issue by Toby-TheEnglishMechanic** [dalathegreat/BatteryUpgrade-UserManual#17] opened 2021-03-22 06:54 UTC
Last week, after the most recent update, on my 24kwh to 40kwh upgrade from last Xmas, I tested the response on Chademo - I hardly have to use Chademo these days, so this was purely to test functionality - warning lights came up on both displays, although the car was fully driveable, with limited régen.
The SOC feedback appears incorrect too, I was at around 55% when charging started. 
I appreciate the last remaining 4 codes are 'expected' but the rest occurred with the Chademo test..... 

![image](https://user-images.githubusercontent.com/76704752/111950952-484ac100-8ae3-11eb-95bd-f4660802fa55.jpeg)

![image](https://user-images.githubusercontent.com/76704752/111950995-54368300-8ae3-11eb-86e1-4f7e27bdb03d.jpeg)

![image](https://user-images.githubusercontent.com/76704752/111951029-5d275480-8ae3-11eb-968b-0c62751538f3.jpeg)

![image](https://user-images.githubusercontent.com/76704752/111951060-67e1e980-8ae3-11eb-996d-ab5a4557a8b3.jpeg)

**Comment by dalathegreat** [comment] 2021-03-22 08:07
The CheckEV light is a known issue, duplicate of https://github.com/dalathegreat/BatteryUpgrade-UserManual/issues/3

The incorrectly scaled SOC% is also known issue, it depends on each chargers implementation of the charging protocol. Some stations read the SOC sent by car, others calculate it internally. This can cause the charge to stop prematurely on some chargers.

I would say we close this and create a new one with the SOC% scaled incorrectly. Sound good?

**Comment by Toby-TheEnglishMechanic** [comment] 2021-03-22 09:11
Morning!!

Yes, indeed, that sounds good, thankyou!

Sorry I didn't spot the duplication I wrote!

Will you do the honours, close this and open a new one, or better if I do??

Thanks

T




Sent from my iPhone - sorry if there any  'predictive' errors :-)


On 22 Mar 2021, at 09:08, Daniel Öster ***@***.***> wrote:

﻿

The CheckEV light is a known issue, duplicate of #3<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdalathegreat%2FBatteryUpgrade-UserManual%2Fissues%2F3&data=04%7C01%7C%7Cdf5d5fb02605409081c608d8ed09a143%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637519972900992421%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=G06qMBoHapQjt0V5m7t%2Bd2cXXjzChQTOsn%2BwHd%2BuqCw%3D&reserved=0>

The incorrectly scaled SOC% is also known issue, it depends on each chargers implementation of the charging protocol. Some stations read the SOC sent by car, others calculate it internally. This can cause the charge to stop prematurely on some chargers.

I would say we close this and create a new one with the SOC% scaled incorrectly. Sound good?

**Closed** 2021-03-22 09:24 UTC

**Comment by dalathegreat** [comment] 2021-03-22 09:29
Created https://github.com/dalathegreat/BatteryUpgrade-UserManual/issues/18
